spring.application.name=HistoricalStockDataService
server.port=8081

#MongoDB Configuration
spring.data.mongodb.uri=mongodb://mongodb:27017/stockdb

#Redis Configuration
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379

#Alpha Vantage Key
alpha.vantage.api.key = HWQ0O4W9OMHM7CW6
alpha.vantage.base_url = https://www.alphavantage.co/query

logging.level.org.springframework=DEBUG
logging.level.com.shiva.trading=DEBUG
